added offset
IntegraSDL/pygats pull request #104
Opened 2023-10-22 11:02 UTC by RiMikheev

Added an offset to determine coordinates when searching for words in certain areas of image

2023-10-23 11:37 UTC, ProjectMutilation requested changes

2023-10-23 11:37 UTC, ProjectMutilation commented on src/pygats/recog.py
> +    return (x_offset, y_offset, img_crop)
extra braces

2023-10-23 11:37 UTC, ProjectMutilation commented on src/pygats/recog.py
> +            pos = ROI(pos[0] + x_offset, pos[1] + y_offset, pos[2], pos[3])
```
roi = ROI(pos[0] + x_offset, pos[1] + y_offset, pos[2], pos[3])
found = True
```
extra calling of assignment

2023-10-27 07:30 UTC, RiMikheev commented on src/pygats/recog.py
> +    return (x_offset, y_offset, img_crop)
fixed

2023-10-27 07:39 UTC, ProjectMutilation commented
LGTM

2023-10-27 07:48 UTC, merged