testing commit for pull_requests
IntegraSDL/pygats pull request #124
Opened 2024-10-07 20:57 UTC by Giovaaanniii

try 2 do pull request

2024-10-09 10:56 UTC, ProjectMutilation requested changes

2024-10-09 10:56 UTC, ProjectMutilation commented on src/pygats/pygats.py
> +import yaml
зачем это изменение?

2024-10-09 10:56 UTC, ProjectMutilation commented on tests/test_pygats.py
> +@pytest.fixture(name="create_ctx")
у фикстуры следует указать скоуп явно

2024-10-09 10:56 UTC, ProjectMutilation commented on tests/test_pygats.py
> +class Test_pygats:
в соглашении об переменных - имена классов UpperCamelCase

2024-10-13 18:28 UTC, Giovaaanniii commented on src/pygats/pygats.py
> -    function prints test suite name in reports
missclick

2024-10-14 12:03 UTC, RiMikheev commented on tests/test_pygats.py
> +from pygats.pygats import __step, __screenshot, __passed, __failed
Зачем, если есть `from pygats.pygats import *`?

2024-10-14 12:04 UTC, RiMikheev commented on tests/test_pygats.py
>      assert ctx
assert в фикстуре

2024-10-14 12:05 UTC, RiMikheev commented on tests/test_pygats.py
> +    STEP_INDEX = 0
Зануление перед тестами не нужно, т.к. оно происходит **после** каждого теста

2024-10-14 12:15 UTC, RiMikheev commented on tests/test_pygats.py
> +)
- Что тут проверяется?
- Зачем указывать явно параметр `TestException`, если это единственное ожидаемое поведение?
- Зачем тут параметризация?

2024-10-14 12:15 UTC, RiMikheev commented on tests/test_pygats.py
> +    if character_set != "" and string_length > 0:
Условие в тесте

2024-10-14 12:18 UTC, RiMikheev commented on tests/test_pygats.py
> +            ("/home/muervos/pygats_folder/pygats/output/Screenshot from 2024-10-13 20-34-25.png", does_not_raise()),
`/home/muervos/pygats_folder/pygats/output/Screenshot from 2024-10-13 20-34-25.png` локальный path

2024-10-15 14:41 UTC, ProjectMutilation commented on src/pygats/pygats.py
> +    elif character_set == "":
не нужно плодить костыли, нужно проверку выше исправить

2024-10-15 14:43 UTC, ProjectMutilation commented on src/pygats/pygats.py
> +        raise IndexError("Cannot choose from an empty sequence")
если изменяешь поведение функции таким образом это должно быть задокументировано в докстринге

2024-10-15 14:48 UTC, ProjectMutilation commented on .pylintrc
> +max-positional-arguments=6
не нужно править линтер, это зона ответственности мейнтейнеров.   
Если нужно подавить в определенном месте, есть `# pylint: disable=%error code%`

2024-10-15 15:02 UTC, ProjectMutilation commented on src/pygats/pygats.py
> +    except pyautogui.ImageNotFoundException or OSError:
при добавлении тестов НЕ следует изменять функциональность, особенно не до конца понимая механизмы языка  
or в данном случае не будет оператором выбора одного из двух исключений

2024-10-23 13:36 UTC, ProjectMutilation commented on tests/test_recog.py
> +def test_rectangle_center_coords():
какой смысл покрывать такое тестами?

2024-11-22 13:49 UTC, Giovaaanniii commented
I am closing the PL due to the fact that it contains old code that was changed in the Pl "clean up tests"

2024-11-22 13:49 UTC, closed without merging