Creating a program to change the background to try tesseract to check the text
IntegraSDL/pygats pull request #139
Opened 2024-11-03 22:37 UTC by Giovaaanniii

I wrote a function that changes the color of the image, and also wrote a small test to check if the tesseract detects text in the final image

2024-11-17 18:25 UTC, vsysoev requested changes
Please do some cleanup

2024-11-17 18:25 UTC, vsysoev commented on tests/find/gen.py
> +        size (tuple): Specifying the size of the image to be created
size is also optional

2024-11-17 18:25 UTC, vsysoev commented on tests/find/gen.py
> +        # if item[0]>200 and item[1]<80 and item[2]<80:
These comments should be removed

2024-11-18 07:10 UTC, vsysoev commented
Goal: Define limit of function check_text. Define constraints for tesseract recognition functions

2024-11-20 14:35 UTC, Giovaaanniii commented
incorrectly created branch

2024-11-20 14:35 UTC, closed without merging