Add a function to search for key points in the image
IntegraSDL/pygats pull request #157
Opened 2024-12-19 21:52 UTC by Giovaaanniii

Text recognition will be based on key points. The key points are the interesting areas of the image. Interesting areas are those areas that are heterogeneous. For example, these can be angles, as there is a sharp change in intensity in two different directions

Conclusion: understand in which areas there is a sharp change in color intensity

2024-12-20 06:01 UTC, vsysoev commented
Interface of the function should be something like:

input image 
returned value keypoints

Plotting might be in some sort of tools which is used find_keypoints function

2024-12-20 06:14 UTC, vsysoev requested changes
Function find_keypoints might be exported. Please pay attention to API, documentation and tests

2025-01-13 07:21 UTC, Giovaaanniii commented on src/pygats/recog.py
> +def clust_keypoints(descrip, clust_count: int):
change func name

2025-01-13 07:27 UTC, Giovaaanniii commented on src/pygats/recog.py
> +def clust_keypoints(descrip, clust_count: int):
clusters / groups

2025-01-29 21:45 UTC, closed without merging